$(document).ready(function(){
  //alert("hi")
  $("#one").click(function(){
    	$("#two").show();
    	});
      $("#one").click(function(){
        	$("#three").show();
        	});
          $("#one").click(function(){
            	$("#four").show();
            	});
              $("#four").click(function(){
                	$("#five").show();
                	});
                  $("#four").click(function(){
                    	$("#six").show();
                    	});
                      $("#four").click(function(){
                        	$("#seven").show();
                        	});
                          $("#four").click(function(){
                            	$("#eight").show();
                            	});
                              $("#eight").click(function(){
                                	$("#nine").show();
                                	});
                                  $("#eight").click(function(){
                                    	$("#ten").show();
                                    	});
                                      $("#eight").click(function(){
                                        	$("#eleven").show();
                                        	});
                                          $("#eight").click(function(){
                                            	$("#twelve").show();
                                            	});
                                              $("#eight").click(function(){
                                                	$("#thirteen").show();
                                                	});
                                                  $("#eight").click(function(){
                                                    	$("#fourteen").show();
                                                    	});
                                                      $("#fourteen").click(function(){
                                                        	$("#fifteen").show();
                                                        	});
                                                          $("#fourteen").click(function(){
                                                            	$("#sixteen").show();
                                                            	});
                                                              $("#fourteen").click(function(){
                                                                	$("#seventeen").show();
                                                                	});
                                                                  $("#fourteen").click(function(){
                                                                    	$("#eighteen").show();
                                                                    	});
                                                                      $("#fourteen").click(function(){
                                                                        	$("#nineteen").show();
                                                                        	});
                                                                          $("#nineteen").click(function(){
                                                                              $("#twenty").show();
                                                                              });
                                                                              $("#nineteen").click(function(){
                                                                                  $("#tone").show();
                                                                                  });
                                                                                  $("#nineteen").click(function(){
                                                                                      $("#ttwo").show();
                                                                                      });
                                                                                      $("#nineteen").click(function(){
                                                                                          $("#tthree").show();
                                                                                          });
                                                                                          $("#tthree").click(function(){
                                                                                              $("#tfour").show();
                                                                                              });
                                                                                              $("#tthree").click(function(){
                                                                                                  $("#tfive").show();
                                                                                                  });
                                                                                                  $("#tthree").click(function(){
                                                                                                      $("#tsix").show();
                                                                                                      });
                                                                                                      $("#tthree").click(function(){
                                                                                                          $("#tseven").show();
                                                                                                          });
                                                                                                          $("#tseven").click(function(){
                                                                                                              $("#run").show();
                                                                                                              });
                                                                                                              $("#tseven").click(function(){
                                                                                                                  $("#door").show();
                                                                                                                  });
                                                                                                                  $("#tseven").click(function(){
                                                                                                                      $("#green").show();
                                                                                                                      });
                                                                                                                      $("#tseven").click(function(){
                                                                                                                          $("#record").show();
                                                                                                                          });
                                                                                                                          $("#tseven").click(function(){
                                                                                                                              $("#closet").show();
                                                                                                                              });
                                                                                                                              $("#tseven").click(function(){
                                                                                                                                  $("#guitar").show();
                                                                                                                                  });
                                                                                                                                  $("#record").click(function(){
                                                                                                                                    	$("#lyrics").show();
                                                                                                                                    	});
                                                                                                                                      /*$("#green").click(function(){
                                                                                                                                        	$("#greengif").show();
                                                                                                                                        });
                                                                                                                                          $("#guitar").click(function(){
                                                                                                                                            	$("#guitargif").show();
                                                                                                                                            });
                                                                                                                                            $("#door").click(function(){
                                                                                                                                              	$("#doorgif").show();
                                                                                                                                              });
                                                                                                                                              $("#record").click(function(){
                                                                                                                                                	$("#recordgif").show();
                                                                                                                                                });
                                                                                                                                                $("#closet").click(function(){
                                                                                                                                                  	$("#closetgif").show();
                                                                                                                                                  });*/